# Build script
init:
  - git config --global core.autocrlf true

image: Visual Studio 2022

# Build script
build_script:
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 --target AppVeyor

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - master
    - develop
