//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Cake.SqlTools")]
[assembly: AssemblyVersion("0.0.9")]
[assembly: AssemblyFileVersion("0.0.9")]
[assembly: AssemblyInformationalVersion("0.0.9")]
[assembly: AssemblyCopyright("Copyright (c) 2015 - 2017 Phillip Sharpe")]

